import { createFeatureSelector, createSelector } from '@ngrx/store';
import { AuthState } from '../state/auth.state';

export const selectAuthState = createFeatureSelector<AuthState>('auth');
export const selectUser = createSelector(selectAuthState, (state) => state.user);
export const selectAccessToken = createSelector(selectAuthState, (state) => state.accessToken);
export const selectCorrelationId = createSelector(selectAuthState, (state) => state.correlationId);
export const selectIsAuthenticated = createSelector(selectAuthState, (state) => state.isAuthenticated);
export const selectUserId = createSelector(selectUser, (user) => user?.userId ?? null);
export const selectRole = createSelector(selectUser, (user) => user?.role ?? null);
export const selectPermissions = createSelector(selectUser, (user) => user?.permissions ?? []);
export const selectLoading = createSelector(selectAuthState, (state) => state.loading);
export const selectError = createSelector(selectAuthState, (state) => state.error);
export const selectAccountLock = createSelector(selectAuthState, (state) => state.accountLock);
export const selectSuccessMessage = createSelector(selectAuthState, (state) => state.successMessage);
export const selectNotice = createSelector(selectAuthState, (state) => state.notice);
export const selectResetPasswordLoading = createSelector(selectAuthState, (state) => state.resetPasswordLoading);
export const selectResetPasswordSuccess = createSelector(selectAuthState, (state) => state.resetPasswordSuccess);
export const selectResetPasswordMessage = createSelector(selectAuthState, (state) => state.resetPasswordMessage);
export const selectResetPasswordError = createSelector(selectAuthState, (state) => state.resetPasswordError);
export const selectResetPasswordData = createSelector(selectAuthState, (state) => state.resetPasswordData);
